"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``biochemistry`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-biochemistry")

@mcp.tool(description='Analyzes circular dichroism (CD) spectroscopy data to determine secondary structure and thermal stability.')
def analyze_circular_dichroism_spectra(sample_name: str, sample_type: str, wavelength_data: list, cd_signal_data: list, temperature_data: list = None, thermal_cd_data: list = None, output_dir: str = './') -> str:
    """BiOMNI wrapper: analyze_circular_dichroism_spectra from biochemistry."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("biochemistry")
        fn = getattr(mod, "analyze_circular_dichroism_spectra")
        wavelength_data_arr = coerce_array(wavelength_data, ndim=1)
        cd_signal_data_arr = coerce_array(cd_signal_data, ndim=1)
        temperature_data_arr = coerce_array(temperature_data, ndim=1)
        thermal_cd_data_arr = coerce_array(thermal_cd_data, ndim=1)
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_circular_dichroism_spectra')
        return call_with_error_boundary(
            "analyze_circular_dichroism_spectra",
            fn,
            sample_name=sample_name,
            sample_type=sample_type,
            wavelength_data=wavelength_data_arr,
            cd_signal_data=cd_signal_data_arr,
            temperature_data=temperature_data_arr,
            thermal_cd_data=thermal_cd_data_arr,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_circular_dichroism_spectra")
@mcp.tool(description='Calculate numeric values for various structural features of an RNA secondary structure.')
def analyze_rna_secondary_structure_features(dot_bracket_structure: str, sequence: str = None) -> str:
    """BiOMNI wrapper: analyze_rna_secondary_structure_features from biochemistry."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("biochemistry")
        fn = getattr(mod, "analyze_rna_secondary_structure_features")
        pass
        return call_with_error_boundary(
            "analyze_rna_secondary_structure_features",
            fn,
            dot_bracket_structure=dot_bracket_structure,
            sequence=sequence,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_rna_secondary_structure_features")
@mcp.tool(description='Analyze protease kinetics data from fluorogenic peptide cleavage assays, fit the data to Michaelis-Menten kinetics, and determine key kinetic parameters.')
def analyze_protease_kinetics(time_points: list, fluorescence_data: list, substrate_concentrations: list, enzyme_concentration: float, output_prefix: str = 'protease_kinetics', output_dir: str = './') -> str:
    """BiOMNI wrapper: analyze_protease_kinetics from biochemistry."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("biochemistry")
        fn = getattr(mod, "analyze_protease_kinetics")
        time_points_arr = coerce_array(time_points, ndim=1)
        fluorescence_data_arr = coerce_array(fluorescence_data, ndim=1)
        substrate_concentrations_arr = coerce_array(substrate_concentrations, ndim=1)
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_protease_kinetics')
        return call_with_error_boundary(
            "analyze_protease_kinetics",
            fn,
            time_points=time_points_arr,
            fluorescence_data=fluorescence_data_arr,
            substrate_concentrations=substrate_concentrations_arr,
            enzyme_concentration=enzyme_concentration,
            output_prefix=output_prefix,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_protease_kinetics")
@mcp.tool(description='Performs in vitro enzyme kinetics assay and analyzes the dose-dependent effects of modulators.')
def analyze_enzyme_kinetics_assay(enzyme_name: str, substrate_concentrations: list, enzyme_concentration: float, modulators: dict = None, time_points: list = None, output_dir: str = './') -> str:
    """BiOMNI wrapper: analyze_enzyme_kinetics_assay from biochemistry."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("biochemistry")
        fn = getattr(mod, "analyze_enzyme_kinetics_assay")
        substrate_concentrations_arr = coerce_array(substrate_concentrations, ndim=1)
        time_points_arr = coerce_array(time_points, ndim=1)
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_enzyme_kinetics_assay')
        return call_with_error_boundary(
            "analyze_enzyme_kinetics_assay",
            fn,
            enzyme_name=enzyme_name,
            substrate_concentrations=substrate_concentrations_arr,
            enzyme_concentration=enzyme_concentration,
            modulators=modulators,
            time_points=time_points_arr,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_enzyme_kinetics_assay")
@mcp.tool(description='Perform multiple sequence alignment and phylogenetic analysis to identify conserved protein regions.')
def analyze_protein_conservation(protein_sequences: list[str], output_dir: str = './') -> str:
    """BiOMNI wrapper: analyze_protein_conservation from biochemistry."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("biochemistry")
        fn = getattr(mod, "analyze_protein_conservation")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_protein_conservation')
        return call_with_error_boundary(
            "analyze_protein_conservation",
            fn,
            protein_sequences=protein_sequences,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_protein_conservation")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
