"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``bioimaging`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-bioimaging")

@mcp.tool(description='Split a 4D NIfTI file into separate modality files for nnUNet processing. Handles BRATS dataset format with FLAIR, T1w, t1gd, and T2w modalities.')
def split_modalities(input_file: str, output_dir: str, case_name: str = 'BRAT') -> str:
    """BiOMNI wrapper: split_modalities from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "split_modalities")
        output_dir_norm = normalize_output_dir(output_dir, 'split_modalities')
        return call_with_error_boundary(
            "split_modalities",
            fn,
            input_file=input_file,
            output_dir=output_dir_norm,
            case_name=case_name,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="split_modalities")
@mcp.tool(description='Prepare input data for nnUNet by handling both 4D and pre-split modality files. Automatically detects file format and prepares data accordingly.')
def prepare_input_for_nnunet(input_path: str, output_dir: str, case_name: str = 'BRAT') -> str:
    """BiOMNI wrapper: prepare_input_for_nnunet from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "prepare_input_for_nnunet")
        output_dir_norm = normalize_output_dir(output_dir, 'prepare_input_for_nnunet')
        return call_with_error_boundary(
            "prepare_input_for_nnunet",
            fn,
            input_path=input_path,
            output_dir=output_dir_norm,
            case_name=case_name,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="prepare_input_for_nnunet")
@mcp.tool(description='Segment images using nnUNet with proper environment setup. Supports brain tumor segmentation and other medical image segmentation tasks.')
def segment_with_nn_unet(image_path: str, output_dir: str, task_id: str, model_type: str = '3d_fullres', folds: list = [0, 1, 2, 3, 4], use_tta: bool = False, num_threads: int = 1, mixed_precision: bool = True, verbose: bool = True, auto_prepare_input: bool = True, results_folder: str = None) -> str:
    """BiOMNI wrapper: segment_with_nn_unet from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "segment_with_nn_unet")
        output_dir_norm = normalize_output_dir(output_dir, 'segment_with_nn_unet')
        return call_with_error_boundary(
            "segment_with_nn_unet",
            fn,
            image_path=image_path,
            output_dir=output_dir_norm,
            task_id=task_id,
            model_type=model_type,
            folds=folds,
            use_tta=use_tta,
            num_threads=num_threads,
            mixed_precision=mixed_precision,
            verbose=verbose,
            auto_prepare_input=auto_prepare_input,
            results_folder=results_folder,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="segment_with_nn_unet")
@mcp.tool(description='Create and save visualization of segmentation results using nilearn. Generates overlay plots and multiple anatomical views.')
def create_segmentation_visualization(original_mri: str, segmentation: str, output_dir: str = './visualization_output') -> str:
    """BiOMNI wrapper: create_segmentation_visualization from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "create_segmentation_visualization")
        output_dir_norm = normalize_output_dir(output_dir, 'create_segmentation_visualization')
        return call_with_error_boundary(
            "create_segmentation_visualization",
            fn,
            original_mri=original_mri,
            segmentation=segmentation,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="create_segmentation_visualization")
@mcp.tool(description='Perform rigid image registration between two medical images using SimpleITK. Rigid registration handles translation and rotation only, preserving shape and size. Includes preprocessing, similarity metrics calculation, and visualization generation.')
def quick_rigid_registration(fixed_image_path: str, moving_image_path: str, output_dir: str, metric: str = 'mutual_information', optimizer: str = 'gradient_descent', preprocess: bool = True, create_visualizations: bool = True, learning_rate: float = 0.01, number_of_iterations: int = 100, gradient_convergence_tolerance: float = 1e-06) -> str:
    """BiOMNI wrapper: quick_rigid_registration from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "quick_rigid_registration")
        output_dir_norm = normalize_output_dir(output_dir, 'quick_rigid_registration')
        return call_with_error_boundary(
            "quick_rigid_registration",
            fn,
            fixed_image_path=fixed_image_path,
            moving_image_path=moving_image_path,
            output_dir=output_dir_norm,
            metric=metric,
            optimizer=optimizer,
            preprocess=preprocess,
            create_visualizations=create_visualizations,
            learning_rate=learning_rate,
            number_of_iterations=number_of_iterations,
            gradient_convergence_tolerance=gradient_convergence_tolerance,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="quick_rigid_registration")
@mcp.tool(description='Perform affine image registration between two medical images using SimpleITK. Affine registration handles translation, rotation, scaling, and shearing. More flexible than rigid registration but still preserves parallel lines.')
def quick_affine_registration(fixed_image_path: str, moving_image_path: str, output_dir: str, metric: str = 'mutual_information', optimizer: str = 'gradient_descent', preprocess: bool = True, create_visualizations: bool = True, learning_rate: float = 0.01, number_of_iterations: int = 100, gradient_convergence_tolerance: float = 1e-06) -> str:
    """BiOMNI wrapper: quick_affine_registration from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "quick_affine_registration")
        output_dir_norm = normalize_output_dir(output_dir, 'quick_affine_registration')
        return call_with_error_boundary(
            "quick_affine_registration",
            fn,
            fixed_image_path=fixed_image_path,
            moving_image_path=moving_image_path,
            output_dir=output_dir_norm,
            metric=metric,
            optimizer=optimizer,
            preprocess=preprocess,
            create_visualizations=create_visualizations,
            learning_rate=learning_rate,
            number_of_iterations=number_of_iterations,
            gradient_convergence_tolerance=gradient_convergence_tolerance,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="quick_affine_registration")
@mcp.tool(description='Perform deformable (B-spline) image registration between two medical images using SimpleITK. Deformable registration allows for local non-linear transformations, handling complex deformations. Most flexible but computationally intensive registration method.')
def quick_deformable_registration(fixed_image_path: str, moving_image_path: str, output_dir: str, metric: str = 'mutual_information', optimizer: str = 'gradient_descent', preprocess: bool = True, create_visualizations: bool = True, learning_rate: float = 0.01, number_of_iterations: int = 100, gradient_convergence_tolerance: float = 1e-06, number_of_control_points: int = 4) -> str:
    """BiOMNI wrapper: quick_deformable_registration from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "quick_deformable_registration")
        output_dir_norm = normalize_output_dir(output_dir, 'quick_deformable_registration')
        return call_with_error_boundary(
            "quick_deformable_registration",
            fn,
            fixed_image_path=fixed_image_path,
            moving_image_path=moving_image_path,
            output_dir=output_dir_norm,
            metric=metric,
            optimizer=optimizer,
            preprocess=preprocess,
            create_visualizations=create_visualizations,
            learning_rate=learning_rate,
            number_of_iterations=number_of_iterations,
            gradient_convergence_tolerance=gradient_convergence_tolerance,
            number_of_control_points=number_of_control_points,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="quick_deformable_registration")
@mcp.tool(description='Perform batch registration of multiple images to a single reference image. Automatically processes all medical image files in a directory and registers them to the fixed reference. Supports rigid, affine, or deformable registration for all images.')
def batch_register_images(fixed_image_path: str, moving_images_dir: str, output_dir: str, transform_type: str = 'rigid', metric: str = 'mutual_information', optimizer: str = 'gradient_descent', preprocess: bool = True, create_visualizations: bool = True, learning_rate: float = 0.01, number_of_iterations: int = 100, gradient_convergence_tolerance: float = 1e-06) -> str:
    """BiOMNI wrapper: batch_register_images from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "batch_register_images")
        output_dir_norm = normalize_output_dir(output_dir, 'batch_register_images')
        return call_with_error_boundary(
            "batch_register_images",
            fn,
            fixed_image_path=fixed_image_path,
            moving_images_dir=moving_images_dir,
            output_dir=output_dir_norm,
            transform_type=transform_type,
            metric=metric,
            optimizer=optimizer,
            preprocess=preprocess,
            create_visualizations=create_visualizations,
            learning_rate=learning_rate,
            number_of_iterations=number_of_iterations,
            gradient_convergence_tolerance=gradient_convergence_tolerance,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="batch_register_images")
@mcp.tool(description='Calculate similarity metrics between two medical images. Supports mutual information, mean squared error, correlation, and normalized cross correlation.')
def calculate_similarity_metrics(image1_path: str, image2_path: str) -> str:
    """BiOMNI wrapper: calculate_similarity_metrics from bioimaging."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("bioimaging")
        fn = getattr(mod, "calculate_similarity_metrics")
        pass
        return call_with_error_boundary(
            "calculate_similarity_metrics",
            fn,
            image1_path=image1_path,
            image2_path=image2_path,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="calculate_similarity_metrics")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
