"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``cancer_biology`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-cancer_biology")

@mcp.tool(description='Analyze DNA Damage Response (DDR) network alterations and dependencies in cancer samples.')
def analyze_ddr_network_in_cancer(expression_data_path: str, mutation_data_path: str, output_dir: str = './results') -> str:
    """BiOMNI wrapper: analyze_ddr_network_in_cancer from cancer_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cancer_biology")
        fn = getattr(mod, "analyze_ddr_network_in_cancer")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_ddr_network_in_cancer')
        return call_with_error_boundary(
            "analyze_ddr_network_in_cancer",
            fn,
            expression_data_path=expression_data_path,
            mutation_data_path=mutation_data_path,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_ddr_network_in_cancer")
@mcp.tool(description='Analyze flow cytometry data to quantify senescent and apoptotic cell populations.')
def analyze_cell_senescence_and_apoptosis(fcs_file_path: str) -> str:
    """BiOMNI wrapper: analyze_cell_senescence_and_apoptosis from cancer_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cancer_biology")
        fn = getattr(mod, "analyze_cell_senescence_and_apoptosis")
        pass
        return call_with_error_boundary(
            "analyze_cell_senescence_and_apoptosis",
            fn,
            fcs_file_path=fcs_file_path,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_cell_senescence_and_apoptosis")
@mcp.tool(description='Detects and annotates somatic mutations in tumor samples compared to matched normal samples using GATK Mutect2 for variant calling, GATK FilterMutectCalls for filtering, and SnpEff for functional annotation.')
def detect_and_annotate_somatic_mutations(tumor_bam: str, normal_bam: str, reference_genome: str, output_prefix: str, snpeff_database: str = 'GRCh38.105') -> str:
    """BiOMNI wrapper: detect_and_annotate_somatic_mutations from cancer_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cancer_biology")
        fn = getattr(mod, "detect_and_annotate_somatic_mutations")
        pass
        return call_with_error_boundary(
            "detect_and_annotate_somatic_mutations",
            fn,
            tumor_bam=tumor_bam,
            normal_bam=normal_bam,
            reference_genome=reference_genome,
            output_prefix=output_prefix,
            snpeff_database=snpeff_database,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="detect_and_annotate_somatic_mutations")
@mcp.tool(description='Detects and characterizes structural variations (SVs) in genomic sequencing data using LUMPY for SV detection followed by annotation with COSMIC and/or ClinVar databases.')
def detect_and_characterize_structural_variations(bam_file_path: str, reference_genome_path: str, output_dir: str, cosmic_db_path: str = None, clinvar_db_path: str = None) -> str:
    """BiOMNI wrapper: detect_and_characterize_structural_variations from cancer_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cancer_biology")
        fn = getattr(mod, "detect_and_characterize_structural_variations")
        output_dir_norm = normalize_output_dir(output_dir, 'detect_and_characterize_structural_variations')
        return call_with_error_boundary(
            "detect_and_characterize_structural_variations",
            fn,
            bam_file_path=bam_file_path,
            reference_genome_path=reference_genome_path,
            output_dir=output_dir_norm,
            cosmic_db_path=cosmic_db_path,
            clinvar_db_path=clinvar_db_path,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="detect_and_characterize_structural_variations")
@mcp.tool(description='Performs Non-negative Matrix Factorization (NMF) on gene expression data to extract metagenes and their associated sample weights for tumor subtype identification.')
def perform_gene_expression_nmf_analysis(expression_data_path: str, n_components: int = 10, normalize: bool = True, output_dir: str = 'nmf_results', random_state: int = 42) -> str:
    """BiOMNI wrapper: perform_gene_expression_nmf_analysis from cancer_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cancer_biology")
        fn = getattr(mod, "perform_gene_expression_nmf_analysis")
        output_dir_norm = normalize_output_dir(output_dir, 'perform_gene_expression_nmf_analysis')
        return call_with_error_boundary(
            "perform_gene_expression_nmf_analysis",
            fn,
            expression_data_path=expression_data_path,
            n_components=n_components,
            normalize=normalize,
            output_dir=output_dir_norm,
            random_state=random_state,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="perform_gene_expression_nmf_analysis")
@mcp.tool(description='CNVkit-based copy number workflow performing CNV segmentation, purity & ploidy approximation, simplified HRD-style metrics, and focal amplification/deletion detection in selected genes.')
def analyze_copy_number_purity_ploidy_and_focal_events(tumor_bam: str, reference_genome: str, normal_bam: str = None, output_dir: str = 'cn_analysis_results', targets_bed: str = None, antitargets_bed: str = None, gene_bed: str = None, focal_genes: str = None, log2_amp_threshold: float = 1.0, log2_del_threshold: float = -1.0) -> str:
    """BiOMNI wrapper: analyze_copy_number_purity_ploidy_and_focal_events from cancer_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cancer_biology")
        fn = getattr(mod, "analyze_copy_number_purity_ploidy_and_focal_events")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_copy_number_purity_ploidy_and_focal_events')
        return call_with_error_boundary(
            "analyze_copy_number_purity_ploidy_and_focal_events",
            fn,
            tumor_bam=tumor_bam,
            reference_genome=reference_genome,
            normal_bam=normal_bam,
            output_dir=output_dir_norm,
            targets_bed=targets_bed,
            antitargets_bed=antitargets_bed,
            gene_bed=gene_bed,
            focal_genes=focal_genes,
            log2_amp_threshold=log2_amp_threshold,
            log2_del_threshold=log2_del_threshold,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_copy_number_purity_ploidy_and_focal_events")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
