"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``cell_biology`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-cell_biology")

@mcp.tool(description='Quantify the percentage of cells in each cell cycle phase using Calcofluor white stained microscopy images.')
def quantify_cell_cycle_phases_from_microscopy(image_paths: str, output_dir: str = './results') -> str:
    """BiOMNI wrapper: quantify_cell_cycle_phases_from_microscopy from cell_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cell_biology")
        fn = getattr(mod, "quantify_cell_cycle_phases_from_microscopy")
        output_dir_norm = normalize_output_dir(output_dir, 'quantify_cell_cycle_phases_from_microscopy')
        return call_with_error_boundary(
            "quantify_cell_cycle_phases_from_microscopy",
            fn,
            image_paths=image_paths,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="quantify_cell_cycle_phases_from_microscopy")
@mcp.tool(description='Quantify cell motility features from time-lapse microscopy images and cluster cells based on motility patterns.')
def quantify_and_cluster_cell_motility(image_sequence_path: str, output_dir: str = './results', num_clusters: int = 3) -> str:
    """BiOMNI wrapper: quantify_and_cluster_cell_motility from cell_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cell_biology")
        fn = getattr(mod, "quantify_and_cluster_cell_motility")
        output_dir_norm = normalize_output_dir(output_dir, 'quantify_and_cluster_cell_motility')
        return call_with_error_boundary(
            "quantify_and_cluster_cell_motility",
            fn,
            image_sequence_path=image_sequence_path,
            output_dir=output_dir_norm,
            num_clusters=num_clusters,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="quantify_and_cluster_cell_motility")
@mcp.tool(description='Performs Fluorescence-Activated Cell Sorting (FACS) to enrich cell populations based on fluorescence characteristics.')
def perform_facs_cell_sorting(cell_suspension_data: str, fluorescence_parameter: str, threshold_min: float = None, threshold_max: float = None, output_file: str = 'sorted_cells.csv') -> str:
    """BiOMNI wrapper: perform_facs_cell_sorting from cell_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cell_biology")
        fn = getattr(mod, "perform_facs_cell_sorting")
        pass
        return call_with_error_boundary(
            "perform_facs_cell_sorting",
            fn,
            cell_suspension_data=cell_suspension_data,
            fluorescence_parameter=fluorescence_parameter,
            threshold_min=threshold_min,
            threshold_max=threshold_max,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="perform_facs_cell_sorting")
@mcp.tool(description='Analyze flow cytometry data to identify and quantify specific cell populations based on surface markers.')
def analyze_flow_cytometry_immunophenotyping(fcs_file_path: str, gating_strategy: dict, compensation_matrix: list = None, output_dir: str = './results') -> str:
    """BiOMNI wrapper: analyze_flow_cytometry_immunophenotyping from cell_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cell_biology")
        fn = getattr(mod, "analyze_flow_cytometry_immunophenotyping")
        compensation_matrix_arr = coerce_array(compensation_matrix, ndim=1)
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_flow_cytometry_immunophenotyping')
        return call_with_error_boundary(
            "analyze_flow_cytometry_immunophenotyping",
            fn,
            fcs_file_path=fcs_file_path,
            gating_strategy=gating_strategy,
            compensation_matrix=compensation_matrix_arr,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_flow_cytometry_immunophenotyping")
@mcp.tool(description='Quantifies metrics of mitochondrial morphology and membrane potential from fluorescence microscopy images.')
def analyze_mitochondrial_morphology_and_potential(morphology_image_path: str, potential_image_path: str, output_dir: str = './output') -> str:
    """BiOMNI wrapper: analyze_mitochondrial_morphology_and_potential from cell_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("cell_biology")
        fn = getattr(mod, "analyze_mitochondrial_morphology_and_potential")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_mitochondrial_morphology_and_potential')
        return call_with_error_boundary(
            "analyze_mitochondrial_morphology_and_potential",
            fn,
            morphology_image_path=morphology_image_path,
            potential_image_path=potential_image_path,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_mitochondrial_morphology_and_potential")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
