"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``database`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-database")

@mcp.tool(description='Query the UniProt REST API using either natural language or a direct endpoint.')
def query_uniprot(prompt: str, endpoint: str = None, max_results: int = 5) -> str:
    """BiOMNI wrapper: query_uniprot from database."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("database")
        fn = getattr(mod, "query_uniprot")
        pass
        return call_with_error_boundary(
            "query_uniprot",
            fn,
            prompt=prompt,
            endpoint=endpoint,
            max_results=max_results,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_uniprot")
@mcp.tool(description='Query the RCSB PDB database using natural language or a direct structured query.')
def query_pdb(prompt: str, query: dict = None, max_results: int = 3) -> str:
    """BiOMNI wrapper: query_pdb from database."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("database")
        fn = getattr(mod, "query_pdb")
        pass
        return call_with_error_boundary(
            "query_pdb",
            fn,
            prompt=prompt,
            query=query,
            max_results=max_results,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_pdb")
@mcp.tool(description='Query the OpenFDA API using natural language or direct parameters.')
def query_openfda(prompt: str, endpoint: str = None, max_results: int = 100, verbose: bool = True, search_params: dict = None, sort_params: dict = None, count_params: str = None, skip_results: int = 0) -> str:
    """BiOMNI wrapper: query_openfda from database."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("database")
        fn = getattr(mod, "query_openfda")
        pass
        return call_with_error_boundary(
            "query_openfda",
            fn,
            prompt=prompt,
            endpoint=endpoint,
            max_results=max_results,
            verbose=verbose,
            search_params=search_params,
            sort_params=sort_params,
            count_params=count_params,
            skip_results=skip_results,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_openfda")
@mcp.tool(description='Query the PubChem PUG-REST API using natural language or a direct endpoint.')
def query_pubchem(prompt: str, endpoint: str = None, max_results: int = 5, verbose: bool = True) -> str:
    """BiOMNI wrapper: query_pubchem from database."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("database")
        fn = getattr(mod, "query_pubchem")
        pass
        return call_with_error_boundary(
            "query_pubchem",
            fn,
            prompt=prompt,
            endpoint=endpoint,
            max_results=max_results,
            verbose=verbose,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_pubchem")
@mcp.tool(description='Query the ChEMBL REST API via natural language, direct endpoint, or identifiers (chembl_id, smiles, molecule_name).')
def query_chembl(prompt: str, endpoint: str = None, chembl_id: str = None, smiles: str = None, molecule_name: str = None, max_results: int = 20, verbose: bool = True) -> str:
    """BiOMNI wrapper: query_chembl from database."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("database")
        fn = getattr(mod, "query_chembl")
        pass
        return call_with_error_boundary(
            "query_chembl",
            fn,
            prompt=prompt,
            endpoint=endpoint,
            chembl_id=chembl_id,
            smiles=smiles,
            molecule_name=molecule_name,
            max_results=max_results,
            verbose=verbose,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_chembl")
@mcp.tool(description='Query the ClinicalTrials.gov API v2 using natural language or a direct endpoint.')
def query_clinicaltrials(prompt: str, endpoint: str = None, max_results: int = 10, verbose: bool = True) -> str:
    """BiOMNI wrapper: query_clinicaltrials from database."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("database")
        fn = getattr(mod, "query_clinicaltrials")
        pass
        return call_with_error_boundary(
            "query_clinicaltrials",
            fn,
            prompt=prompt,
            endpoint=endpoint,
            max_results=max_results,
            verbose=verbose,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_clinicaltrials")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
