"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``genetics`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-genetics")

@mcp.tool(description='Perform liftover of genomic coordinates between hg19 and hg38 formats with detailed intermediate steps.')
def liftover_coordinates(chromosome: str, position: int, input_format: str, output_format: str, data_path: str) -> str:
    """BiOMNI wrapper: liftover_coordinates from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "liftover_coordinates")
        pass
        return call_with_error_boundary(
            "liftover_coordinates",
            fn,
            chromosome=chromosome,
            position=position,
            input_format=input_format,
            output_format=output_format,
            data_path=data_path,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="liftover_coordinates")
@mcp.tool(description='Analyzes and categorizes mutations induced by Cas9 at target sites.')
def analyze_cas9_mutation_outcomes(reference_sequences: dict, edited_sequences: dict, cell_line_info: dict = None, output_prefix: str = 'cas9_mutation_analysis') -> str:
    """BiOMNI wrapper: analyze_cas9_mutation_outcomes from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "analyze_cas9_mutation_outcomes")
        pass
        return call_with_error_boundary(
            "analyze_cas9_mutation_outcomes",
            fn,
            reference_sequences=reference_sequences,
            edited_sequences=edited_sequences,
            cell_line_info=cell_line_info,
            output_prefix=output_prefix,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_cas9_mutation_outcomes")
@mcp.tool(description='Analyzes CRISPR-Cas9 genome editing results by comparing original and edited sequences.')
def analyze_crispr_genome_editing(original_sequence: str, edited_sequence: str, guide_rna: str, repair_template: str = None) -> str:
    """BiOMNI wrapper: analyze_crispr_genome_editing from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "analyze_crispr_genome_editing")
        pass
        return call_with_error_boundary(
            "analyze_crispr_genome_editing",
            fn,
            original_sequence=original_sequence,
            edited_sequence=edited_sequence,
            guide_rna=guide_rna,
            repair_template=repair_template,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_crispr_genome_editing")
@mcp.tool(description='Simulate DNA sequences with specified demographic and coalescent histories using msprime.')
def simulate_demographic_history(num_samples: int = 10, sequence_length: int = 100000, recombination_rate: float = 1e-08, mutation_rate: float = 1e-08, demographic_model: str = 'constant', demographic_params: dict = None, coalescent_model: str = 'kingman', beta_coalescent_param: float = None, random_seed: int = None, output_file: str = 'simulated_sequences.vcf') -> str:
    """BiOMNI wrapper: simulate_demographic_history from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "simulate_demographic_history")
        pass
        return call_with_error_boundary(
            "simulate_demographic_history",
            fn,
            num_samples=num_samples,
            sequence_length=sequence_length,
            recombination_rate=recombination_rate,
            mutation_rate=mutation_rate,
            demographic_model=demographic_model,
            demographic_params=demographic_params,
            coalescent_model=coalescent_model,
            beta_coalescent_param=beta_coalescent_param,
            random_seed=random_seed,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="simulate_demographic_history")
@mcp.tool(description='Identifies binding sites for a specific transcription factor in a genomic sequence.')
def identify_transcription_factor_binding_sites(sequence: str, tf_name: str, threshold: float = 0.8, output_file: str = None) -> str:
    """BiOMNI wrapper: identify_transcription_factor_binding_sites from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "identify_transcription_factor_binding_sites")
        pass
        return call_with_error_boundary(
            "identify_transcription_factor_binding_sites",
            fn,
            sequence=sequence,
            tf_name=tf_name,
            threshold=threshold,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="identify_transcription_factor_binding_sites")
@mcp.tool(description='Fit a linear mixed model for genomic prediction using genotype and phenotype data.')
def fit_genomic_prediction_model(genotypes: list, phenotypes: list, fixed_effects: list = None, model_type: str = 'additive', output_file: str = 'genomic_prediction_results.csv') -> str:
    """BiOMNI wrapper: fit_genomic_prediction_model from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "fit_genomic_prediction_model")
        genotypes_arr = coerce_array(genotypes, ndim=1)
        phenotypes_arr = coerce_array(phenotypes, ndim=1)
        fixed_effects_arr = coerce_array(fixed_effects, ndim=1)
        return call_with_error_boundary(
            "fit_genomic_prediction_model",
            fn,
            genotypes=genotypes_arr,
            phenotypes=phenotypes_arr,
            fixed_effects=fixed_effects_arr,
            model_type=model_type,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="fit_genomic_prediction_model")
@mcp.tool(description='Performs PCR amplification of a target transgene and visualizes results using agarose gel electrophoresis.')
def perform_pcr_and_gel_electrophoresis(genomic_dna: str, forward_primer: str = None, reverse_primer: str = None, target_region: str = None, annealing_temp: float = 58, extension_time: int = 30, cycles: int = 35, gel_percentage: float = 2.0, output_prefix: str = 'pcr_result') -> str:
    """BiOMNI wrapper: perform_pcr_and_gel_electrophoresis from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "perform_pcr_and_gel_electrophoresis")
        pass
        return call_with_error_boundary(
            "perform_pcr_and_gel_electrophoresis",
            fn,
            genomic_dna=genomic_dna,
            forward_primer=forward_primer,
            reverse_primer=reverse_primer,
            target_region=target_region,
            annealing_temp=annealing_temp,
            extension_time=extension_time,
            cycles=cycles,
            gel_percentage=gel_percentage,
            output_prefix=output_prefix,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="perform_pcr_and_gel_electrophoresis")
@mcp.tool(description='Perform phylogenetic analysis on a set of protein sequences. This function aligns sequences, constructs a phylogenetic tree, and visualizes evolutionary relationships.')
def analyze_protein_phylogeny(fasta_sequences: str, output_dir: str = './', alignment_method: str = 'clustalw', tree_method: str = 'fasttree') -> str:
    """BiOMNI wrapper: analyze_protein_phylogeny from genetics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genetics")
        fn = getattr(mod, "analyze_protein_phylogeny")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_protein_phylogeny')
        return call_with_error_boundary(
            "analyze_protein_phylogeny",
            fn,
            fasta_sequences=fasta_sequences,
            output_dir=output_dir_norm,
            alignment_method=alignment_method,
            tree_method=tree_method,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_protein_phylogeny")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
