"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``genomics`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-genomics")

@mcp.tool(description='Annotate cell types based on gene markers and transferred labels using LLM. After leiden clustering, annotate clusters using differentially expressed genes and optionally incorporate transferred labels from reference datasets.')
def annotate_celltype_scRNA(adata_filename: str, data_dir: str, data_info: str, data_lake_path: str, cluster: str = 'leiden', llm: str = 'claude-3-5-sonnet-20241022', composition: str = None) -> str:
    """BiOMNI wrapper: annotate_celltype_scRNA from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "annotate_celltype_scRNA")
        pass
        return call_with_error_boundary(
            "annotate_celltype_scRNA",
            fn,
            adata_filename=adata_filename,
            data_dir=data_dir,
            data_info=data_info,
            data_lake_path=data_lake_path,
            cluster=cluster,
            llm=llm,
            composition=composition,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="annotate_celltype_scRNA")
@mcp.tool(description='Perform cell type annotation of single-cell RNA-seq data using Panhuman Azimuth Neural Network. This function implements the Panhuman Azimuth workflow for cell type annotation using the panhumanpy package, providing hierarchical cell type labels for tissues across the human body.')
def annotate_celltype_with_panhumanpy(adata_path: str, feature_names_col: str = None, refine: bool = True, umap: bool = True, output_dir: str = './output') -> str:
    """BiOMNI wrapper: annotate_celltype_with_panhumanpy from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "annotate_celltype_with_panhumanpy")
        output_dir_norm = normalize_output_dir(output_dir, 'annotate_celltype_with_panhumanpy')
        return call_with_error_boundary(
            "annotate_celltype_with_panhumanpy",
            fn,
            adata_path=adata_path,
            feature_names_col=feature_names_col,
            refine=refine,
            umap=umap,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="annotate_celltype_with_panhumanpy")
@mcp.tool(description='Create scVI and scANVI embeddings for single-cell RNA-seq data, saving the results to an AnnData object.')
def create_scvi_embeddings_scRNA(adata_filename: str, batch_key: str, label_key: str, data_dir: str) -> str:
    """BiOMNI wrapper: create_scvi_embeddings_scRNA from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "create_scvi_embeddings_scRNA")
        pass
        return call_with_error_boundary(
            "create_scvi_embeddings_scRNA",
            fn,
            adata_filename=adata_filename,
            batch_key=batch_key,
            label_key=label_key,
            data_dir=data_dir,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="create_scvi_embeddings_scRNA")
@mcp.tool(description='Performs batch integration on single-cell RNA-seq data using Harmony and saves the integrated embeddings.')
def create_harmony_embeddings_scRNA(adata_filename: str, batch_key: str, data_dir: str) -> str:
    """BiOMNI wrapper: create_harmony_embeddings_scRNA from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "create_harmony_embeddings_scRNA")
        pass
        return call_with_error_boundary(
            "create_harmony_embeddings_scRNA",
            fn,
            adata_filename=adata_filename,
            batch_key=batch_key,
            data_dir=data_dir,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="create_harmony_embeddings_scRNA")
@mcp.tool(description='Generate UCE embeddings for single-cell RNA-seq data and map them to a reference dataset for cell type annotation.')
def get_uce_embeddings_scRNA(adata_filename: str, data_dir: str, DATA_ROOT: str = '/dfs/project/bioagentos/data/singlecell/', custom_args: str = None) -> str:
    """BiOMNI wrapper: get_uce_embeddings_scRNA from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "get_uce_embeddings_scRNA")
        pass
        return call_with_error_boundary(
            "get_uce_embeddings_scRNA",
            fn,
            adata_filename=adata_filename,
            data_dir=data_dir,
            DATA_ROOT=DATA_ROOT,
            custom_args=custom_args,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_uce_embeddings_scRNA")
@mcp.tool(description='Map cell embeddings from the input dataset to the Integrated Megascale Atlas reference dataset using UCE embeddings.')
def map_to_ima_interpret_scRNA(adata_filename: str, data_dir: str, custom_args: dict = None) -> str:
    """BiOMNI wrapper: map_to_ima_interpret_scRNA from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "map_to_ima_interpret_scRNA")
        pass
        return call_with_error_boundary(
            "map_to_ima_interpret_scRNA",
            fn,
            adata_filename=adata_filename,
            data_dir=data_dir,
            custom_args=custom_args,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="map_to_ima_interpret_scRNA")
@mcp.tool(description='Given a gene name, fetch RNA-seq expression data showing the top K tissues with highest transcripts-per-million (TPM) values.')
def get_rna_seq_archs4(gene_name: str, K: int = 10) -> str:
    """BiOMNI wrapper: get_rna_seq_archs4 from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "get_rna_seq_archs4")
        pass
        return call_with_error_boundary(
            "get_rna_seq_archs4",
            fn,
            gene_name=gene_name,
            K=K,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_rna_seq_archs4")
@mcp.tool(description='Returns a list of supported databases for gene set enrichment analysis.')
def get_gene_set_enrichment_analysis_supported_database_list() -> str:
    """BiOMNI wrapper: get_gene_set_enrichment_analysis_supported_database_list from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "get_gene_set_enrichment_analysis_supported_database_list")
        pass
        return call_with_error_boundary(
            "get_gene_set_enrichment_analysis_supported_database_list",
            fn,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_gene_set_enrichment_analysis_supported_database_list")
@mcp.tool(description='Perform enrichment analysis for a list of genes, with optional background gene set and plotting functionality.')
def gene_set_enrichment_analysis(genes: list, top_k: int = 10, database: str = 'ontology', background_list: list = None, plot: bool = False) -> str:
    """BiOMNI wrapper: gene_set_enrichment_analysis from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "gene_set_enrichment_analysis")
        pass
        return call_with_error_boundary(
            "gene_set_enrichment_analysis",
            fn,
            genes=genes,
            top_k=top_k,
            database=database,
            background_list=background_list,
            plot=plot,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="gene_set_enrichment_analysis")
@mcp.tool(description='Analyze chromatin interactions from Hi-C data to identify enhancer-promoter interactions and TADs.')
def analyze_chromatin_interactions(hic_file_path: str, regulatory_elements_bed: str, output_dir: str = './output') -> str:
    """BiOMNI wrapper: analyze_chromatin_interactions from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "analyze_chromatin_interactions")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_chromatin_interactions')
        return call_with_error_boundary(
            "analyze_chromatin_interactions",
            fn,
            hic_file_path=hic_file_path,
            regulatory_elements_bed=regulatory_elements_bed,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_chromatin_interactions")
@mcp.tool(description='Perform comparative genomics and haplotype analysis on multiple genome samples. Aligns genome samples to a reference, identifies variants, analyzes shared and unique genomic regions, and determines haplotype structure.')
def analyze_comparative_genomics_and_haplotypes(sample_fasta_files: str, reference_genome_path: str, output_dir: str = './output') -> str:
    """BiOMNI wrapper: analyze_comparative_genomics_and_haplotypes from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "analyze_comparative_genomics_and_haplotypes")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_comparative_genomics_and_haplotypes')
        return call_with_error_boundary(
            "analyze_comparative_genomics_and_haplotypes",
            fn,
            sample_fasta_files=sample_fasta_files,
            reference_genome_path=reference_genome_path,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_comparative_genomics_and_haplotypes")
@mcp.tool(description='Perform ChIP-seq peak calling using MACS2 to identify genomic regions with significant binding.')
def perform_chipseq_peak_calling_with_macs2(chip_seq_file: str, control_file: str, output_name: str = 'macs2_output', genome_size: str = 'hs', q_value: float = 0.05) -> str:
    """BiOMNI wrapper: perform_chipseq_peak_calling_with_macs2 from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "perform_chipseq_peak_calling_with_macs2")
        pass
        return call_with_error_boundary(
            "perform_chipseq_peak_calling_with_macs2",
            fn,
            chip_seq_file=chip_seq_file,
            control_file=control_file,
            output_name=output_name,
            genome_size=genome_size,
            q_value=q_value,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="perform_chipseq_peak_calling_with_macs2")
@mcp.tool(description='Find DNA sequence motifs enriched in genomic regions using the HOMER motif discovery software.')
def find_enriched_motifs_with_homer(peak_file: str, genome: str = 'hg38', background_file: str = None, motif_length: str = '8,10,12', output_dir: str = './homer_motifs', num_motifs: int = 10, threads: int = 4) -> str:
    """BiOMNI wrapper: find_enriched_motifs_with_homer from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "find_enriched_motifs_with_homer")
        output_dir_norm = normalize_output_dir(output_dir, 'find_enriched_motifs_with_homer')
        return call_with_error_boundary(
            "find_enriched_motifs_with_homer",
            fn,
            peak_file=peak_file,
            genome=genome,
            background_file=background_file,
            motif_length=motif_length,
            output_dir=output_dir_norm,
            num_motifs=num_motifs,
            threads=threads,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="find_enriched_motifs_with_homer")
@mcp.tool(description='Analyze overlaps between two or more sets of genomic regions.')
def analyze_genomic_region_overlap(region_sets: list, output_prefix: str = 'overlap_analysis') -> str:
    """BiOMNI wrapper: analyze_genomic_region_overlap from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "analyze_genomic_region_overlap")
        pass
        return call_with_error_boundary(
            "analyze_genomic_region_overlap",
            fn,
            region_sets=region_sets,
            output_prefix=output_prefix,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_genomic_region_overlap")
@mcp.tool(description="Transfer cell type labels from an annotated reference scRNA-seq dataset to an unannotated query dataset using popV. Loads both AnnData .h5ad files, prepares count layers for scVI, processes the query against the reference, and runs selected annotation methods (default: SCANVI_POPV). Saves predictions to 'output_folder/popv_output/predictions.csv'. This function allows you to use different annotaiton methods i.e. CELLTYPIST, KNN_BBKNN, KNN_HARMONY, KNN_SCANORAMA, KNN_SCVI, ONCLASS, Random_Forest, SCANVI_POPV, Support_Vector, XGboost. Based on you transfer task you can select the multiple best annotation methods. Beware each annotation method adds computational requirements for running the tool. By default it uses SCANVI_POPV method.")
def unsupervised_celltype_transfer_between_scRNA_datasets(path_to_annotated_h5ad: str, path_to_not_annotated_h5ad: str, ref_labels_key: str, query_batch_key: str = None, ref_batch_key: str = None, CELLTYPIST: bool = False, KNN_BBKNN: bool = False, KNN_HARMONY: bool = False, KNN_SCANORAMA: bool = False, KNN_SCVI: bool = False, ONCLASS: bool = False, Random_Forest: bool = False, SCANVI_POPV: bool = True, Support_Vector: bool = False, XGboost: bool = False, n_jobs: int = 1, output_folder: str = './tmp/', n_samples_per_label: int = 10) -> str:
    """BiOMNI wrapper: unsupervised_celltype_transfer_between_scRNA_datasets from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "unsupervised_celltype_transfer_between_scRNA_datasets")
        pass
        return call_with_error_boundary(
            "unsupervised_celltype_transfer_between_scRNA_datasets",
            fn,
            path_to_annotated_h5ad=path_to_annotated_h5ad,
            path_to_not_annotated_h5ad=path_to_not_annotated_h5ad,
            ref_labels_key=ref_labels_key,
            query_batch_key=query_batch_key,
            ref_batch_key=ref_batch_key,
            CELLTYPIST=CELLTYPIST,
            KNN_BBKNN=KNN_BBKNN,
            KNN_HARMONY=KNN_HARMONY,
            KNN_SCANORAMA=KNN_SCANORAMA,
            KNN_SCVI=KNN_SCVI,
            ONCLASS=ONCLASS,
            Random_Forest=Random_Forest,
            SCANVI_POPV=SCANVI_POPV,
            Support_Vector=Support_Vector,
            XGboost=XGboost,
            n_jobs=n_jobs,
            output_folder=output_folder,
            n_samples_per_label=n_samples_per_label,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="unsupervised_celltype_transfer_between_scRNA_datasets")
@mcp.tool(description='Generate State embeddings for single-cell RNA-seq data using the SE-600M model. This function downloads the SE-600M model from Hugging Face, installs required dependencies (git-lfs, uv, arc-state), and generates embeddings for the input AnnData object. The SE-600M model is a state-of-the-art embedding model for single-cell data that can capture complex biological patterns and cell states. Features include real-time streaming output, automatic retry with reduced batch size on failure, GPU detection and warnings, and input validation.')
def generate_embeddings_with_state(adata_filename: str, data_dir: str, model_folder: str, output_filename: str = None, checkpoint: str = None, embed_key: str = 'X_state', protein_embeddings: str = None, batch_size: int = 500) -> str:
    """BiOMNI wrapper: generate_embeddings_with_state from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "generate_embeddings_with_state")
        pass
        return call_with_error_boundary(
            "generate_embeddings_with_state",
            fn,
            adata_filename=adata_filename,
            data_dir=data_dir,
            model_folder=model_folder,
            output_filename=output_filename,
            checkpoint=checkpoint,
            embed_key=embed_key,
            protein_embeddings=protein_embeddings,
            batch_size=batch_size,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="generate_embeddings_with_state")
@mcp.tool(description='Convert ENSEMBL gene IDs between different species using BioMart homology mapping. This function converts a list of ENSEMBL gene IDs from one species to their homologous counterparts in another species using the Ensembl BioMart database. The conversion is based on one-to-one ortholog mappings between species.')
def interspecies_gene_conversion(gene_list: str, source_species: str, target_species: str) -> str:
    """BiOMNI wrapper: interspecies_gene_conversion from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "interspecies_gene_conversion")
        pass
        return call_with_error_boundary(
            "interspecies_gene_conversion",
            fn,
            gene_list=gene_list,
            source_species=source_species,
            target_species=target_species,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="interspecies_gene_conversion")
@mcp.tool(description='Generate average protein embeddings for a list of Ensembl gene IDs using ESM (Evolutionary Scale Modeling) protein language models. This function fetches all protein isoform sequences for each gene, computes embeddings for each isoform using the specified ESM model and layer, then averages the embeddings across all isoforms to create a single representative embedding per gene. The embeddings are saved as PyTorch tensors for future use. Memory-friendly implementation with rolling averages, small batch processing, and automatic memory management. Automatically handles GPU/CPU device selection and includes error recovery for out-of-memory situations by falling back to single-sequence processing.')
def generate_gene_embeddings_with_ESM_models(ensembl_gene_ids: str, model_name: str = 'esm2_t6_8M_UR50D', layer: int = 6, save_path: str = None, batch_size: int = 1, max_sequence_length: int = 1024) -> str:
    """BiOMNI wrapper: generate_gene_embeddings_with_ESM_models from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "generate_gene_embeddings_with_ESM_models")
        pass
        return call_with_error_boundary(
            "generate_gene_embeddings_with_ESM_models",
            fn,
            ensembl_gene_ids=ensembl_gene_ids,
            model_name=model_name,
            layer=layer,
            save_path=save_path,
            batch_size=batch_size,
            max_sequence_length=max_sequence_length,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="generate_gene_embeddings_with_ESM_models")
@mcp.tool(description="Generate Transcriptformer embeddings for single-cell RNA-seq data. This function downloads model checkpoints, prepares the AnnData object with required fields (ensembl_id, raw counts, assay metadata), and runs inference to generate cell or gene embeddings. Transcriptformer is a transformer-based model that can learn rich representations of single-cell gene expression data. The function automatically handles Ensembl ID pattern detection, model downloading, data preprocessing, and creates missing assay metadata columns with 'unknown' values if needed.")
def generate_transcriptformer_embeddings(adata_filename: str, data_dir: str, output_filename: str = None, model_type: str = 'tf-sapiens', checkpoint_path: str = None, batch_size: int = 8, precision: str = '16-mixed', clip_counts: int = 30, embedding_layer_index: int = -1, num_gpus: int = 1, n_data_workers: int = 0, gene_col_name: str = 'ensembl_id', pretrained_embedding: str = None, filter_to_vocabs: bool = True, use_raw: str = 'None', emb_type: str = 'cell', remove_duplicate_genes: bool = False, oom_dataloader: bool = False) -> str:
    """BiOMNI wrapper: generate_transcriptformer_embeddings from genomics."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("genomics")
        fn = getattr(mod, "generate_transcriptformer_embeddings")
        pass
        return call_with_error_boundary(
            "generate_transcriptformer_embeddings",
            fn,
            adata_filename=adata_filename,
            data_dir=data_dir,
            output_filename=output_filename,
            model_type=model_type,
            checkpoint_path=checkpoint_path,
            batch_size=batch_size,
            precision=precision,
            clip_counts=clip_counts,
            embedding_layer_index=embedding_layer_index,
            num_gpus=num_gpus,
            n_data_workers=n_data_workers,
            gene_col_name=gene_col_name,
            pretrained_embedding=pretrained_embedding,
            filter_to_vocabs=filter_to_vocabs,
            use_raw=use_raw,
            emb_type=emb_type,
            remove_duplicate_genes=remove_duplicate_genes,
            oom_dataloader=oom_dataloader,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="generate_transcriptformer_embeddings")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
