"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``immunology`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-immunology")

@mcp.tool(description='Perform ATAC-seq peak calling and differential accessibility analysis using MACS2.')
def analyze_atac_seq_differential_accessibility(treatment_bam: str, control_bam: str, output_dir: str = './atac_results', genome_size: str = 'hs', q_value: float = 0.05, name_prefix: str = 'atac') -> str:
    """BiOMNI wrapper: analyze_atac_seq_differential_accessibility from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "analyze_atac_seq_differential_accessibility")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_atac_seq_differential_accessibility')
        return call_with_error_boundary(
            "analyze_atac_seq_differential_accessibility",
            fn,
            treatment_bam=treatment_bam,
            control_bam=control_bam,
            output_dir=output_dir_norm,
            genome_size=genome_size,
            q_value=q_value,
            name_prefix=name_prefix,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_atac_seq_differential_accessibility")
@mcp.tool(description='Analyzes bacterial growth curve data to determine growth parameters such as doubling time, growth rate, and lag phase.')
def analyze_bacterial_growth_curve(time_points: str, od_values: str, strain_name: str, output_dir: str = '.') -> str:
    """BiOMNI wrapper: analyze_bacterial_growth_curve from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "analyze_bacterial_growth_curve")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_bacterial_growth_curve')
        return call_with_error_boundary(
            "analyze_bacterial_growth_curve",
            fn,
            time_points=time_points,
            od_values=od_values,
            strain_name=strain_name,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_bacterial_growth_curve")
@mcp.tool(description='Simulates the isolation and purification of immune cells from tissue samples.')
def isolate_purify_immune_cells(tissue_type: str, target_cell_type: str, enzyme_type: str = 'collagenase', macs_antibody: str = None, digestion_time_min: int = 45) -> str:
    """BiOMNI wrapper: isolate_purify_immune_cells from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "isolate_purify_immune_cells")
        pass
        return call_with_error_boundary(
            "isolate_purify_immune_cells",
            fn,
            tissue_type=tissue_type,
            target_cell_type=target_cell_type,
            enzyme_type=enzyme_type,
            macs_antibody=macs_antibody,
            digestion_time_min=digestion_time_min,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="isolate_purify_immune_cells")
@mcp.tool(description='Estimate cell cycle phase durations using dual-nucleoside pulse labeling data and mathematical modeling.')
def estimate_cell_cycle_phase_durations(flow_cytometry_data: dict, initial_estimates: dict) -> str:
    """BiOMNI wrapper: estimate_cell_cycle_phase_durations from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "estimate_cell_cycle_phase_durations")
        pass
        return call_with_error_boundary(
            "estimate_cell_cycle_phase_durations",
            fn,
            flow_cytometry_data=flow_cytometry_data,
            initial_estimates=initial_estimates,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="estimate_cell_cycle_phase_durations")
@mcp.tool(description='Track immune cells under flow conditions and classify their behaviors.')
def track_immune_cells_under_flow(image_sequence_path: str, output_dir: str = './output', pixel_size_um: float = 1.0, time_interval_sec: float = 1.0, flow_direction: str = 'right') -> str:
    """BiOMNI wrapper: track_immune_cells_under_flow from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "track_immune_cells_under_flow")
        output_dir_norm = normalize_output_dir(output_dir, 'track_immune_cells_under_flow')
        return call_with_error_boundary(
            "track_immune_cells_under_flow",
            fn,
            image_sequence_path=image_sequence_path,
            output_dir=output_dir_norm,
            pixel_size_um=pixel_size_um,
            time_interval_sec=time_interval_sec,
            flow_direction=flow_direction,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="track_immune_cells_under_flow")
@mcp.tool(description='Analyze CFSE-labeled cell samples to quantify cell division and proliferation.')
def analyze_cfse_cell_proliferation(fcs_file_path: str, cfse_channel: str = 'FL1-A', lymphocyte_gate: str = None) -> str:
    """BiOMNI wrapper: analyze_cfse_cell_proliferation from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "analyze_cfse_cell_proliferation")
        pass
        return call_with_error_boundary(
            "analyze_cfse_cell_proliferation",
            fn,
            fcs_file_path=fcs_file_path,
            cfse_channel=cfse_channel,
            lymphocyte_gate=lymphocyte_gate,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_cfse_cell_proliferation")
@mcp.tool(description='Analyze cytokine production (IFN-γ, IL-17) in CD4+ T cells after antigen stimulation.')
def analyze_cytokine_production_in_cd4_tcells(fcs_files_dict: dict, output_dir: str = './results') -> str:
    """BiOMNI wrapper: analyze_cytokine_production_in_cd4_tcells from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "analyze_cytokine_production_in_cd4_tcells")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_cytokine_production_in_cd4_tcells')
        return call_with_error_boundary(
            "analyze_cytokine_production_in_cd4_tcells",
            fn,
            fcs_files_dict=fcs_files_dict,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_cytokine_production_in_cd4_tcells")
@mcp.tool(description='Analyze ELISA data to quantify EBV antibody titers in plasma/serum samples.')
def analyze_ebv_antibody_titers(raw_od_data: dict, standard_curve_data: dict, sample_metadata: dict, output_dir: str = './') -> str:
    """BiOMNI wrapper: analyze_ebv_antibody_titers from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "analyze_ebv_antibody_titers")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_ebv_antibody_titers')
        return call_with_error_boundary(
            "analyze_ebv_antibody_titers",
            fn,
            raw_od_data=raw_od_data,
            standard_curve_data=standard_curve_data,
            sample_metadata=sample_metadata,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_ebv_antibody_titers")
@mcp.tool(description='Analyzes histological images of CNS lesions to quantify immune cell infiltration, demyelination, and tissue damage.')
def analyze_cns_lesion_histology(image_path: str, output_dir: str = './output', stain_type: str = 'H&E') -> str:
    """BiOMNI wrapper: analyze_cns_lesion_histology from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "analyze_cns_lesion_histology")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_cns_lesion_histology')
        return call_with_error_boundary(
            "analyze_cns_lesion_histology",
            fn,
            image_path=image_path,
            output_dir=output_dir_norm,
            stain_type=stain_type,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_cns_lesion_histology")
@mcp.tool(description='Analyzes immunohistochemistry images to quantify protein expression and spatial distribution.')
def analyze_immunohistochemistry_image(image_path: str, protein_name: str = 'Unknown', output_dir: str = './ihc_results/') -> str:
    """BiOMNI wrapper: analyze_immunohistochemistry_image from immunology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("immunology")
        fn = getattr(mod, "analyze_immunohistochemistry_image")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_immunohistochemistry_image')
        return call_with_error_boundary(
            "analyze_immunohistochemistry_image",
            fn,
            image_path=image_path,
            protein_name=protein_name,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_immunohistochemistry_image")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
