"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``literature`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-literature")

@mcp.tool(description='Query arXiv for papers based on the provided search query.')
def query_arxiv(query: str, max_papers: int = 10) -> str:
    """BiOMNI wrapper: query_arxiv from literature."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("literature")
        fn = getattr(mod, "query_arxiv")
        pass
        return call_with_error_boundary(
            "query_arxiv",
            fn,
            query=query,
            max_papers=max_papers,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_arxiv")
@mcp.tool(description='Query PubMed for papers based on the provided search query.')
def query_pubmed(query: str, max_papers: int = 10, max_retries: int = 3) -> str:
    """BiOMNI wrapper: query_pubmed from literature."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("literature")
        fn = getattr(mod, "query_pubmed")
        pass
        return call_with_error_boundary(
            "query_pubmed",
            fn,
            query=query,
            max_papers=max_papers,
            max_retries=max_retries,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="query_pubmed")
@mcp.tool(description='Extract the text content of a webpage using requests and BeautifulSoup.')
def extract_url_content(url: str) -> str:
    """BiOMNI wrapper: extract_url_content from literature."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("literature")
        fn = getattr(mod, "extract_url_content")
        pass
        return call_with_error_boundary(
            "extract_url_content",
            fn,
            url=url,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="extract_url_content")
@mcp.tool(description='Extract text content from a PDF file.')
def extract_pdf_content(url: str) -> str:
    """BiOMNI wrapper: extract_pdf_content from literature."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("literature")
        fn = getattr(mod, "extract_pdf_content")
        pass
        return call_with_error_boundary(
            "extract_pdf_content",
            fn,
            url=url,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="extract_pdf_content")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
