"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``molecular_biology`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-molecular_biology")

@mcp.tool(description='Find all Open Reading Frames (ORFs) in a DNA sequence using Biopython, searching both forward and reverse complement strands.')
def annotate_open_reading_frames(sequence: str, min_length: int, search_reverse: bool = False, filter_subsets: bool = False) -> str:
    """BiOMNI wrapper: annotate_open_reading_frames from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "annotate_open_reading_frames")
        pass
        return call_with_error_boundary(
            "annotate_open_reading_frames",
            fn,
            sequence=sequence,
            min_length=min_length,
            search_reverse=search_reverse,
            filter_subsets=filter_subsets,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="annotate_open_reading_frames")
@mcp.tool(description="Annotate a DNA sequence using pLannotate's command-line interface.")
def annotate_plasmid(sequence: str, is_circular: bool = True) -> str:
    """BiOMNI wrapper: annotate_plasmid from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "annotate_plasmid")
        pass
        return call_with_error_boundary(
            "annotate_plasmid",
            fn,
            sequence=sequence,
            is_circular=is_circular,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="annotate_plasmid")
@mcp.tool(description='Retrieves the coding sequence(s) of a specified gene from NCBI Entrez.')
def get_gene_coding_sequence(gene_name: str, organism: str, email: str = None) -> str:
    """BiOMNI wrapper: get_gene_coding_sequence from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "get_gene_coding_sequence")
        pass
        return call_with_error_boundary(
            "get_gene_coding_sequence",
            fn,
            gene_name=gene_name,
            organism=organism,
            email=email,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_gene_coding_sequence")
@mcp.tool(description='Unified function to retrieve plasmid sequences from either Addgene or NCBI. If is_addgene is True or identifier is numeric, uses Addgene. Otherwise searches NCBI using the plasmid name.')
def get_plasmid_sequence(identifier: str, is_addgene: bool = None) -> str:
    """BiOMNI wrapper: get_plasmid_sequence from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "get_plasmid_sequence")
        pass
        return call_with_error_boundary(
            "get_plasmid_sequence",
            fn,
            identifier=identifier,
            is_addgene=is_addgene,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_plasmid_sequence")
@mcp.tool(description='Align short sequences (primers) to a longer sequence, allowing for one mismatch. Checks both forward and reverse complement strands.')
def align_sequences(long_seq: str, short_seqs: str) -> str:
    """BiOMNI wrapper: align_sequences from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "align_sequences")
        pass
        return call_with_error_boundary(
            "align_sequences",
            fn,
            long_seq=long_seq,
            short_seqs=short_seqs,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="align_sequences")
@mcp.tool(description='Simulate PCR amplification with given primers and sequence.')
def pcr_simple(sequence: str, forward_primer: str, reverse_primer: str, circular: bool = False) -> str:
    """BiOMNI wrapper: pcr_simple from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "pcr_simple")
        pass
        return call_with_error_boundary(
            "pcr_simple",
            fn,
            sequence=sequence,
            forward_primer=forward_primer,
            reverse_primer=reverse_primer,
            circular=circular,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="pcr_simple")
@mcp.tool(description='Simulates restriction enzyme digestion of a DNA sequence and returns the resulting fragments with their properties.')
def digest_sequence(dna_sequence: str, enzyme_names: str, is_circular: bool = True) -> str:
    """BiOMNI wrapper: digest_sequence from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "digest_sequence")
        pass
        return call_with_error_boundary(
            "digest_sequence",
            fn,
            dna_sequence=dna_sequence,
            enzyme_names=enzyme_names,
            is_circular=is_circular,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="digest_sequence")
@mcp.tool(description='Identifies restriction enzyme sites in a given DNA sequence for specified enzymes.')
def find_restriction_sites(dna_sequence: str, enzymes: str, is_circular: bool = True) -> str:
    """BiOMNI wrapper: find_restriction_sites from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "find_restriction_sites")
        pass
        return call_with_error_boundary(
            "find_restriction_sites",
            fn,
            dna_sequence=dna_sequence,
            enzymes=enzymes,
            is_circular=is_circular,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="find_restriction_sites")
@mcp.tool(description='Finds common restriction enzyme sites in a DNA sequence and returns their cut positions.')
def find_restriction_enzymes(sequence: str, is_circular: bool = False) -> str:
    """BiOMNI wrapper: find_restriction_enzymes from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "find_restriction_enzymes")
        pass
        return call_with_error_boundary(
            "find_restriction_enzymes",
            fn,
            sequence=sequence,
            is_circular=is_circular,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="find_restriction_enzymes")
@mcp.tool(description='Compare query sequence against reference sequence to identify mutations.')
def find_sequence_mutations(query_sequence: str, reference_sequence: str, query_start: int = 1) -> str:
    """BiOMNI wrapper: find_sequence_mutations from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "find_sequence_mutations")
        pass
        return call_with_error_boundary(
            "find_sequence_mutations",
            fn,
            query_sequence=query_sequence,
            reference_sequence=reference_sequence,
            query_start=query_start,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="find_sequence_mutations")
@mcp.tool(description='Design sgRNAs for CRISPR knockout by searching pre-computed sgRNA libraries. Returns optimized guide RNAs for targeting a specific gene.')
def design_knockout_sgrna(gene_name: str, data_lake_path: str, species: str = 'human', num_guides: int = 1) -> str:
    """BiOMNI wrapper: design_knockout_sgrna from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "design_knockout_sgrna")
        pass
        return call_with_error_boundary(
            "design_knockout_sgrna",
            fn,
            gene_name=gene_name,
            data_lake_path=data_lake_path,
            species=species,
            num_guides=num_guides,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="design_knockout_sgrna")
@mcp.tool(description='Return a standard protocol for annealing oligonucleotides without phosphorylation.')
def get_oligo_annealing_protocol() -> str:
    """BiOMNI wrapper: get_oligo_annealing_protocol from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "get_oligo_annealing_protocol")
        pass
        return call_with_error_boundary(
            "get_oligo_annealing_protocol",
            fn,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_oligo_annealing_protocol")
@mcp.tool(description='Return a customized protocol for Golden Gate assembly based on the number of inserts and specific DNA sequences.')
def get_golden_gate_assembly_protocol(enzyme_name: str, vector_length: int, num_inserts: int = 1, vector_amount_ng: float = 75.0, insert_lengths: str = None, is_library_prep: bool = False) -> str:
    """BiOMNI wrapper: get_golden_gate_assembly_protocol from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "get_golden_gate_assembly_protocol")
        pass
        return call_with_error_boundary(
            "get_golden_gate_assembly_protocol",
            fn,
            enzyme_name=enzyme_name,
            vector_length=vector_length,
            num_inserts=num_inserts,
            vector_amount_ng=vector_amount_ng,
            insert_lengths=insert_lengths,
            is_library_prep=is_library_prep,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_golden_gate_assembly_protocol")
@mcp.tool(description='Return a standard protocol for bacterial transformation.')
def get_bacterial_transformation_protocol(antibiotic: str = 'ampicillin', is_repetitive: bool = False) -> str:
    """BiOMNI wrapper: get_bacterial_transformation_protocol from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "get_bacterial_transformation_protocol")
        pass
        return call_with_error_boundary(
            "get_bacterial_transformation_protocol",
            fn,
            antibiotic=antibiotic,
            is_repetitive=is_repetitive,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_bacterial_transformation_protocol")
@mcp.tool(description='Design a single primer within the given sequence window.')
def design_primer(sequence: str, start_pos: int, primer_length: int = 20, min_gc: float = 0.4, max_gc: float = 0.6, min_tm: float = 55.0, max_tm: float = 65.0, search_window: int = 100) -> str:
    """BiOMNI wrapper: design_primer from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "design_primer")
        pass
        return call_with_error_boundary(
            "design_primer",
            fn,
            sequence=sequence,
            start_pos=start_pos,
            primer_length=primer_length,
            min_gc=min_gc,
            max_gc=max_gc,
            min_tm=min_tm,
            max_tm=max_tm,
            search_window=search_window,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="design_primer")
@mcp.tool(description='Design Sanger sequencing primers to verify a specific region in a plasmid. First tries to use primers from an existing primer pool. If they cannot fully cover the region, designs additional primers as needed.')
def design_verification_primers(plasmid_sequence: str, target_region: str, existing_primers: str = None, is_circular: bool = True, coverage_length: int = 800, primer_length: int = 20, min_gc: float = 0.4, max_gc: float = 0.6, min_tm: float = 55.0, max_tm: float = 65.0) -> str:
    """BiOMNI wrapper: design_verification_primers from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "design_verification_primers")
        pass
        return call_with_error_boundary(
            "design_verification_primers",
            fn,
            plasmid_sequence=plasmid_sequence,
            target_region=target_region,
            existing_primers=existing_primers,
            is_circular=is_circular,
            coverage_length=coverage_length,
            primer_length=primer_length,
            min_gc=min_gc,
            max_gc=max_gc,
            min_tm=min_tm,
            max_tm=max_tm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="design_verification_primers")
@mcp.tool(description='Design complementary oligonucleotides with Type IIS restriction enzyme overhangs for Golden Gate assembly based on restriction site analysis of the backbone.')
def design_golden_gate_oligos(backbone_sequence: str, insert_sequence: str, enzyme_name: str, is_circular: bool = True) -> str:
    """BiOMNI wrapper: design_golden_gate_oligos from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "design_golden_gate_oligos")
        pass
        return call_with_error_boundary(
            "design_golden_gate_oligos",
            fn,
            backbone_sequence=backbone_sequence,
            insert_sequence=insert_sequence,
            enzyme_name=enzyme_name,
            is_circular=is_circular,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="design_golden_gate_oligos")
@mcp.tool(description='Simulate Golden Gate assembly to predict final construct sequences from backbone and fragment sequences.')
def golden_gate_assembly(backbone_sequence: str, enzyme_name: str, fragments: str, is_circular: bool = True) -> str:
    """BiOMNI wrapper: golden_gate_assembly from molecular_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("molecular_biology")
        fn = getattr(mod, "golden_gate_assembly")
        pass
        return call_with_error_boundary(
            "golden_gate_assembly",
            fn,
            backbone_sequence=backbone_sequence,
            enzyme_name=enzyme_name,
            fragments=fragments,
            is_circular=is_circular,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="golden_gate_assembly")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
