"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``pharmacology`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-pharmacology")

@mcp.tool(description='Analyze biodistribution and pharmacokinetic profile of radiolabeled antibodies.')
def analyze_radiolabeled_antibody_biodistribution(time_points: str, tissue_data: dict) -> str:
    """BiOMNI wrapper: analyze_radiolabeled_antibody_biodistribution from pharmacology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("pharmacology")
        fn = getattr(mod, "analyze_radiolabeled_antibody_biodistribution")
        pass
        return call_with_error_boundary(
            "analyze_radiolabeled_antibody_biodistribution",
            fn,
            time_points=time_points,
            tissue_data=tissue_data,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_radiolabeled_antibody_biodistribution")
@mcp.tool(description='Estimate radiation absorbed doses to tumor and normal organs for alpha-particle radiotherapeutics using the Medical Internal Radiation Dose (MIRD) schema.')
def estimate_alpha_particle_radiotherapy_dosimetry(biodistribution_data: dict, radiation_parameters: dict, output_file: str = 'dosimetry_results.csv') -> str:
    """BiOMNI wrapper: estimate_alpha_particle_radiotherapy_dosimetry from pharmacology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("pharmacology")
        fn = getattr(mod, "estimate_alpha_particle_radiotherapy_dosimetry")
        pass
        return call_with_error_boundary(
            "estimate_alpha_particle_radiotherapy_dosimetry",
            fn,
            biodistribution_data=biodistribution_data,
            radiation_parameters=radiation_parameters,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="estimate_alpha_particle_radiotherapy_dosimetry")
@mcp.tool(description='Calculate key physicochemical properties of a drug candidate molecule.')
def calculate_physicochemical_properties(smiles_string: str) -> str:
    """BiOMNI wrapper: calculate_physicochemical_properties from pharmacology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("pharmacology")
        fn = getattr(mod, "calculate_physicochemical_properties")
        pass
        return call_with_error_boundary(
            "calculate_physicochemical_properties",
            fn,
            smiles_string=smiles_string,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="calculate_physicochemical_properties")
@mcp.tool(description='Analyze tumor growth inhibition in xenograft models across different treatment groups.')
def analyze_xenograft_tumor_growth_inhibition(data_path: str, time_column: str, volume_column: str, group_column: str, subject_column: str, output_dir: str = './results') -> str:
    """BiOMNI wrapper: analyze_xenograft_tumor_growth_inhibition from pharmacology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("pharmacology")
        fn = getattr(mod, "analyze_xenograft_tumor_growth_inhibition")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_xenograft_tumor_growth_inhibition')
        return call_with_error_boundary(
            "analyze_xenograft_tumor_growth_inhibition",
            fn,
            data_path=data_path,
            time_column=time_column,
            volume_column=volume_column,
            group_column=group_column,
            subject_column=subject_column,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_xenograft_tumor_growth_inhibition")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
