"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``protocols`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-protocols")

@mcp.tool(description='Search protocols.io for public protocols matching a keyword.')
def search_protocols(query: str) -> str:
    """BiOMNI wrapper: search_protocols from protocols."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("protocols")
        fn = getattr(mod, "search_protocols")
        pass
        return call_with_error_boundary(
            "search_protocols",
            fn,
            query=query,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="search_protocols")
@mcp.tool(description='Retrieve detailed metadata for a specific protocols.io protocol by ID.')
def get_protocol_details(protocol_id: int, timeout: int = 30) -> str:
    """BiOMNI wrapper: get_protocol_details from protocols."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("protocols")
        fn = getattr(mod, "get_protocol_details")
        pass
        return call_with_error_boundary(
            "get_protocol_details",
            fn,
            protocol_id=protocol_id,
            timeout=timeout,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="get_protocol_details")
@mcp.tool(description='List available protocol files in the local biomni/tool/protocols/ directory. Includes protocols from Addgene and Thermo Fisher Scientific.')
def list_local_protocols(source: str = None) -> str:
    """BiOMNI wrapper: list_local_protocols from protocols."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("protocols")
        fn = getattr(mod, "list_local_protocols")
        pass
        return call_with_error_boundary(
            "list_local_protocols",
            fn,
            source=source,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="list_local_protocols")
@mcp.tool(description='Read the contents of a local protocol file from biomni/tool/protocols/. Use list_local_protocols() first to find available protocol filenames.')
def read_local_protocol(filename: str, source: str = None) -> str:
    """BiOMNI wrapper: read_local_protocol from protocols."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("protocols")
        fn = getattr(mod, "read_local_protocol")
        pass
        return call_with_error_boundary(
            "read_local_protocol",
            fn,
            filename=filename,
            source=source,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="read_local_protocol")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
