"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``synthetic_biology`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-synthetic_biology")

@mcp.tool(description='Engineer a bacterial genome by integrating therapeutic genetic parts for therapeutic delivery.')
def engineer_bacterial_genome_for_therapeutic_delivery(bacterial_genome_file: str, genetic_parts: dict) -> str:
    """BiOMNI wrapper: engineer_bacterial_genome_for_therapeutic_delivery from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "engineer_bacterial_genome_for_therapeutic_delivery")
        pass
        return call_with_error_boundary(
            "engineer_bacterial_genome_for_therapeutic_delivery",
            fn,
            bacterial_genome_file=bacterial_genome_file,
            genetic_parts=genetic_parts,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="engineer_bacterial_genome_for_therapeutic_delivery")
@mcp.tool(description='Analyze bacterial growth data and extract growth parameters from OD600 measurements.')
def analyze_bacterial_growth_rate(time_points: str, od_measurements: str, strain_name: str = 'Unknown strain', output_dir: str = './') -> str:
    """BiOMNI wrapper: analyze_bacterial_growth_rate from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "analyze_bacterial_growth_rate")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_bacterial_growth_rate')
        return call_with_error_boundary(
            "analyze_bacterial_growth_rate",
            fn,
            time_points=time_points,
            od_measurements=od_measurements,
            strain_name=strain_name,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_bacterial_growth_rate")
@mcp.tool(description='Analyze sequencing data to extract, quantify and determine lineage relationships of barcodes.')
def analyze_barcode_sequencing_data(input_file: str, barcode_pattern: str = None, flanking_seq_5prime: str = None, flanking_seq_3prime: str = None, min_count: int = 5, output_dir: str = './results') -> str:
    """BiOMNI wrapper: analyze_barcode_sequencing_data from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "analyze_barcode_sequencing_data")
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_barcode_sequencing_data')
        return call_with_error_boundary(
            "analyze_barcode_sequencing_data",
            fn,
            input_file=input_file,
            barcode_pattern=barcode_pattern,
            flanking_seq_5prime=flanking_seq_5prime,
            flanking_seq_3prime=flanking_seq_3prime,
            min_count=min_count,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_barcode_sequencing_data")
@mcp.tool(description='Performs bifurcation analysis on a dynamical system and generates a bifurcation diagram.')
def analyze_bifurcation_diagram(time_series_data: list, parameter_values: list, system_name: str = 'Dynamical System', output_dir: str = './') -> str:
    """BiOMNI wrapper: analyze_bifurcation_diagram from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "analyze_bifurcation_diagram")
        time_series_data_arr = coerce_array(time_series_data, ndim=1)
        parameter_values_arr = coerce_array(parameter_values, ndim=1)
        output_dir_norm = normalize_output_dir(output_dir, 'analyze_bifurcation_diagram')
        return call_with_error_boundary(
            "analyze_bifurcation_diagram",
            fn,
            time_series_data=time_series_data_arr,
            parameter_values=parameter_values_arr,
            system_name=system_name,
            output_dir=output_dir_norm,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="analyze_bifurcation_diagram")
@mcp.tool(description='Generate a mathematical model of a biochemical network in SBML format.')
def create_biochemical_network_sbml_model(reaction_network: str, kinetic_parameters: dict, output_file: str = 'biochemical_model.xml') -> str:
    """BiOMNI wrapper: create_biochemical_network_sbml_model from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "create_biochemical_network_sbml_model")
        pass
        return call_with_error_boundary(
            "create_biochemical_network_sbml_model",
            fn,
            reaction_network=reaction_network,
            kinetic_parameters=kinetic_parameters,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="create_biochemical_network_sbml_model")
@mcp.tool(description='Analyzes and optimizes a DNA/RNA sequence for improved expression in a heterologous host organism.')
def optimize_codons_for_heterologous_expression(target_sequence: str, host_codon_usage: dict) -> str:
    """BiOMNI wrapper: optimize_codons_for_heterologous_expression from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "optimize_codons_for_heterologous_expression")
        pass
        return call_with_error_boundary(
            "optimize_codons_for_heterologous_expression",
            fn,
            target_sequence=target_sequence,
            host_codon_usage=host_codon_usage,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="optimize_codons_for_heterologous_expression")
@mcp.tool(description='Simulate gene regulatory circuit dynamics with growth feedback.')
def simulate_gene_circuit_with_growth_feedback(circuit_topology: list, kinetic_params: dict, growth_params: dict, simulation_time: float = 100, time_points: int = 1000) -> str:
    """BiOMNI wrapper: simulate_gene_circuit_with_growth_feedback from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "simulate_gene_circuit_with_growth_feedback")
        circuit_topology_arr = coerce_array(circuit_topology, ndim=1)
        return call_with_error_boundary(
            "simulate_gene_circuit_with_growth_feedback",
            fn,
            circuit_topology=circuit_topology_arr,
            kinetic_params=kinetic_params,
            growth_params=growth_params,
            simulation_time=simulation_time,
            time_points=time_points,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="simulate_gene_circuit_with_growth_feedback")
@mcp.tool(description='Identifies functional domains within a Fatty Acid Synthase (FAS) sequence and predicts their roles.')
def identify_fas_functional_domains(sequence: str, sequence_type: str = 'protein', output_file: str = 'fas_domains_report.txt') -> str:
    """BiOMNI wrapper: identify_fas_functional_domains from synthetic_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("synthetic_biology")
        fn = getattr(mod, "identify_fas_functional_domains")
        pass
        return call_with_error_boundary(
            "identify_fas_functional_domains",
            fn,
            sequence=sequence,
            sequence_type=sequence_type,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="identify_fas_functional_domains")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
