"""Auto-generated by scripts/biomni_codegen.py.

MCP server wrapping the BiOMNI ``systems_biology`` module.
Every wrapper routes through ``tools.biomni.common`` so missing
BiOMNI dependencies surface as a JSON error rather than crashing
the MCP stdio loop.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Make the sciMAS repo root importable when this file is launched
# as a script via ``python tools/biomni/<cat>_server.py`` — without
# this the ``from tools.biomni.common import ...`` lines in every
# wrapper would fail with ModuleNotFoundError because sys.path[0]
# would point at tools/biomni/ instead of the repo root.
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mcp.server.mcpserver import MCPServer

mcp = MCPServer("biomni-systems_biology")

@mcp.tool(description='Perform Flux Balance Analysis (FBA) on a genome-scale metabolic network model and return a research log of the process and results.')
def perform_flux_balance_analysis(model_file: str, constraints: dict = None, objective_reaction: str = None, output_file: str = 'fba_results.csv') -> str:
    """BiOMNI wrapper: perform_flux_balance_analysis from systems_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("systems_biology")
        fn = getattr(mod, "perform_flux_balance_analysis")
        pass
        return call_with_error_boundary(
            "perform_flux_balance_analysis",
            fn,
            model_file=model_file,
            constraints=constraints,
            objective_reaction=objective_reaction,
            output_file=output_file,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="perform_flux_balance_analysis")
@mcp.tool(description='Model protein dimerization networks to find equilibrium concentrations of dimers.')
def model_protein_dimerization_network(monomer_concentrations: dict, dimerization_affinities: dict, network_topology: list) -> str:
    """BiOMNI wrapper: model_protein_dimerization_network from systems_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("systems_biology")
        fn = getattr(mod, "model_protein_dimerization_network")
        pass
        return call_with_error_boundary(
            "model_protein_dimerization_network",
            fn,
            monomer_concentrations=monomer_concentrations,
            dimerization_affinities=dimerization_affinities,
            network_topology=network_topology,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="model_protein_dimerization_network")
@mcp.tool(description='Construct and simulate kinetic models of metabolic networks and analyze their responses to perturbations.')
def simulate_metabolic_network_perturbation(model_file: str, initial_concentrations: dict, perturbation_params: dict, simulation_time: float = 100, time_points: int = 1000) -> str:
    """BiOMNI wrapper: simulate_metabolic_network_perturbation from systems_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("systems_biology")
        fn = getattr(mod, "simulate_metabolic_network_perturbation")
        pass
        return call_with_error_boundary(
            "simulate_metabolic_network_perturbation",
            fn,
            model_file=model_file,
            initial_concentrations=initial_concentrations,
            perturbation_params=perturbation_params,
            simulation_time=simulation_time,
            time_points=time_points,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="simulate_metabolic_network_perturbation")
@mcp.tool(description='Simulate protein signaling network dynamics using ODE-based logic modeling with normalized Hill functions.')
def simulate_protein_signaling_network(network_structure: dict, reaction_params: dict, species_params: dict, simulation_time: float = 100, time_points: int = 1000) -> str:
    """BiOMNI wrapper: simulate_protein_signaling_network from systems_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("systems_biology")
        fn = getattr(mod, "simulate_protein_signaling_network")
        pass
        return call_with_error_boundary(
            "simulate_protein_signaling_network",
            fn,
            network_structure=network_structure,
            reaction_params=reaction_params,
            species_params=species_params,
            simulation_time=simulation_time,
            time_points=time_points,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="simulate_protein_signaling_network")
@mcp.tool(description='Compares two protein structures to identify structural differences and conformational changes.')
def compare_protein_structures(pdb_file1: str, pdb_file2: str, chain_id1: str = 'A', chain_id2: str = 'A', output_prefix: str = 'protein_comparison') -> str:
    """BiOMNI wrapper: compare_protein_structures from systems_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("systems_biology")
        fn = getattr(mod, "compare_protein_structures")
        pass
        return call_with_error_boundary(
            "compare_protein_structures",
            fn,
            pdb_file1=pdb_file1,
            pdb_file2=pdb_file2,
            chain_id1=chain_id1,
            chain_id2=chain_id2,
            output_prefix=output_prefix,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="compare_protein_structures")
@mcp.tool(description='Simulate the time-dependent concentrations of renin-angiotensin system (RAS) components.')
def simulate_renin_angiotensin_system_dynamics(initial_concentrations: dict, rate_constants: dict, feedback_params: dict, simulation_time: float = 48, time_points: int = 100) -> str:
    """BiOMNI wrapper: simulate_renin_angiotensin_system_dynamics from systems_biology."""
    try:
        from tools.biomni.common import (
            call_with_error_boundary,
            coerce_array,
            coerce_dataframe,
            load_biomni_module,
            normalize_output_dir,
            require_positive,
            truncate,
        )
        import json as _json

        mod = load_biomni_module("systems_biology")
        fn = getattr(mod, "simulate_renin_angiotensin_system_dynamics")
        pass
        return call_with_error_boundary(
            "simulate_renin_angiotensin_system_dynamics",
            fn,
            initial_concentrations=initial_concentrations,
            rate_constants=rate_constants,
            feedback_params=feedback_params,
            simulation_time=simulation_time,
            time_points=time_points,
        )
    except Exception as exc:
        from tools.biomni.common import err
        return err(str(exc), tool="simulate_renin_angiotensin_system_dynamics")


if __name__ == "__main__":
    asyncio.run(mcp.run_stdio_async())
